project:
  type: website
  output-dir: docs

website:
  title: "Bold: Research and Development"
  site-url: http://boldresearch.org
  description: Portfolio and blog
  favicon: assets/bold-logo-g.png
  navbar:
    title: "B<span class='icon-line'>"
    right:
      - href: index.qmd
        text: Home
      - href: services.qmd
        text: Services
      - href: posts.qmd
        text: Technical blog
      - href: https://anandphilip.com 
        text: Personal Blog
        target: "_blank"


format:
  html:
    theme: 
      - flatly
      - assets/ap-theme.scss
    toc: true
    link-external-newwindow: true


